# Generated by Django 3.2.5 on 2021-08-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_user'),
        ('files', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='page_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.page'),
            preserve_default=False,
        ),
    ]
